# .github/workflows/generate-snake.yml
# .github/workflows/generate-snake.yml
name: Generate GitHub Contributions Snake

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake SVGs
        uses: platane/snk@v3
        with:
          github_user_name: SirjanSingh
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Commit and push generated SVGs (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage root files
          git add github-snake*.svg || true

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update generated GitHub contributions snake SVGs"
          git push origin HEAD:main
